[package]
name = "wakfudecrypt"
version = "0.1.0"
authors = ["jac3km4 <jac3km4@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
zip = { version = "0.5.6", default-features = false, features = [ "deflate" ] }
